### ISSUE TITLE
Homepage and Docs

### ISSUE THREAD

**Issue by depombo** [alantech/docs#2]
- [x] Buy alanlang.org and alan-lang.org
- [x] High quality documentation
- [x] Copy for homepage (Concurnas didn't get a good response on HackerNews, but one thing that was praised was the homepage: https://news.ycombinator.com/item?id=23321096)
- [x] Forward hello at alantechnologies dot com to admin at alantechnologies dot com
- [x] Add amplitude to homepage and docs
- [x] Web playground to edit and run Alan similar to Rust by example
- [x] Design and deployment in place
- [x] Instrument "Download Alan" CTA
- [x] figure out that social sharing box stuff
so pasting the URL on Twitter/FB/Discord/Slack/etc has a nice preview with our logo and some text

**Comment by dfellis** [comment]
I want to check off that other checkbox, too, but we used segment, not amplitude @depombo :wink:

**Comment by depombo** [comment]
Talked offline, we use both :)
